apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ccm
spec:
  clusterSelector:
    matchLabels:
      caprox.eu/ccm: "true"
  releaseName: ccm
  version: 0.2.22
  repoURL: oci://ghcr.io/sergelogvinov/charts
  namespace: kube-system
  chartName: proxmox-cloud-controller-manager
  valuesTemplate: |
    existingConfigSecret: ccm-config
    {{- if eq (index .Cluster.metadata.labels "caprox.eu/ccm-mode") "daemonset" }}
    useDaemonSet: true
    {{- end }}
    extraVolumes:
      - name: credentials-proxmox
        secret:
          secretName: proxmox-credentials
    extraVolumeMounts:
      - name: credentials-proxmox
        readOnly: true
        mountPath: "/var/run/secrets/proxmox"
    extraEnvs:
      # Use Controlplane Endpoint for in-cluster communication with API Server
      # This is required for CCM to work when the API Server is not accessible via the default service IP (e.g. when using kube-vip with host networking)
      - name: KUBERNETES_SERVICE_HOST
        value: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
      - name: KUBERNETES_SERVICE_PORT
        value: "{{ .Cluster.spec.controlPlaneEndpoint.port }}"

    enabledControllers:
      - cloud-node

    # Deploy CCM only on control-plane nodes
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
