apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: HelmChartProxy
metadata:
  name: calico-cni
spec:
  clusterSelector:
    matchLabels:
      caprox.eu/cni: calico
  repoURL: https://docs.tigera.io/calico/charts
  chartName: tigera-operator
  releaseName: tigera-operator
  version: v3.31.4
  options:
    waitForJobs: true
    wait: true
    timeout: 10m0s
    install:
      createNamespace: true
  valuesTemplate: |
    installation:
      enabled: true
      kubernetesProvider: ""
      cni:
        type: Calico
        ipam:
          type: Calico
      serviceCIDRs:
{{- range $cidr := .Cluster.spec.clusterNetwork.services.cidrBlocks }}
        - {{ $cidr }}
{{- end }}
      calicoNetwork:
        linuxDataplane: Iptables
        windowsDataplane: HNS
        bgp: Disabled
        hostPorts: Enabled
        ipPools:
{{- range $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
          - cidr: {{ $cidr }}
            blockSize: 26
            encapsulation: VXLAN
            natOutgoing: Enabled
            nodeSelector: all()
{{- end }}

    apiServer:
      enabled: true

    kubernetesServiceEndpoint:
      host: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
      port: "{{ .Cluster.spec.controlPlaneEndpoint.port }}"

#Copied from, but still need to research windows specific settings: 
#https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/config/samples/calico-cni.yaml