apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: calico-cni
spec:
  clusterSelector:
    matchLabels:
      caprox.eu/cni: calico
  releaseName: calico
  repoURL: https://docs.tigera.io/calico/charts
  chartName: tigera-operator
  namespace: kube-system
  valuesTemplate: |
    installation:
    cni:
      type: Calico
      ipam:
        type: Calico
    calicoNetwork:
      bgp: Disabled
      windowsDataplane: HNS
      mtu: 1350
      ipPools:{{range $i, $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
      - cidr: {{ $cidr }}
        encapsulation: None
        natOutgoing: Enabled
        nodeSelector: all(){{end}}

#Copied from, but still need to research windows specific settings: 
#https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/config/samples/calico-cni.yaml